apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nhvf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0007-tenant/ci10t-786-0007-app/devfile-sample-nhvf@sha256:368861cf96a277f369d5ca5072a3b7a1baf540df1d91e06190cf8a78d8788cf2
        name: my-nodejs
        resources: {}
status: {}
